/* Glossary of ML terms — used for tooltips and glossary page */
window.GLOSSARY = {
  'accuracy': 'Frazione di predizioni corrette sul totale. Metrica di base per la classificazione, ma poco informativa con classi sbilanciate.',
  'attivazione': 'Funzione non lineare applicata all\'output di un neurone (ReLU, sigmoide, tanh, softmax). Senza attivazioni, un MLP profondo si riduce a un modello lineare.',
  'AUC': 'Area Under the Curve. In ROC-AUC misura la capacità di un classificatore di distinguere le classi indipendentemente dalla soglia scelta. 0.5 = casuale, 1.0 = perfetto.',
  'backpropagation': 'Algoritmo che calcola i gradienti della loss rispetto ai parametri di una rete neurale applicando la regola della catena all\'indietro nel grafo di calcolo.',
  'bagging': 'Bootstrap Aggregating. Tecnica ensemble: addestra molti modelli su campioni bootstrap del dataset e aggrega. Base del Random Forest, riduce la varianza.',
  'baseline': 'Modello semplice usato come termine di paragone. Un modello serio deve battere almeno un baseline (media, majority class, regressione lineare).',
  'bias (statistico)': 'Errore sistematico del modello, distanza tra la previsione media e il vero valore. Modelli semplici hanno bias alto.',
  'bias-variance tradeoff': 'Decomposizione dell\'errore atteso in bias, varianza e rumore irriducibile. Modelli complessi hanno basso bias ma alta varianza, semplici viceversa.',
  'boosting': 'Tecnica ensemble che costruisce modelli in sequenza, ognuno concentrato sugli errori del precedente. XGBoost, LightGBM, CatBoost sono le implementazioni dominanti.',
  'bootstrap': 'Campionamento con reinserimento dai dati. Base del bagging e delle stime di variabilità.',
  'broadcasting': 'Meccanismo di NumPy per operare tra array di shape diverse ma compatibili senza copiare memoria. Alla base della vettorializzazione.',
  'centroide': 'Il punto medio di un cluster in K-Means. L\'algoritmo alterna assegnazione dei punti al centroide più vicino e ricalcolo dei centroidi.',
  'classificazione': 'Compito supervisionato in cui l\'output è discreto (etichette di classe). Binaria se due classi, multi-classe se più.',
  'clustering': 'Compito non supervisionato di raggruppare dati simili senza etichette. K-Means, DBSCAN, gerarchico sono metodi comuni.',
  'convergenza': 'Un algoritmo iterativo converge se la sequenza dei suoi output tende a un limite (spesso un minimo o un ottimo).',
  'cross-entropy': 'Loss standard per la classificazione: $-\\sum_i y_i \\log \\hat p_i$. Deriva dalla massima verosimiglianza sotto distribuzione categorica.',
  'cross-validation': 'Tecnica di valutazione che divide i dati in K fold e ripete K addestramenti/valutazioni. Riduce la varianza della stima di generalizzazione.',
  'DBSCAN': 'Algoritmo di clustering basato sulla densità. Non richiede di specificare il numero di cluster, gestisce outlier automaticamente, funziona con cluster di forma arbitraria.',
  'deep learning': 'Machine learning con reti neurali profonde (molti strati). Domina in visione, linguaggio, audio.',
  'discesa del gradiente': 'Metodo di ottimizzazione che aggiorna i parametri nella direzione opposta al gradiente della loss. Con learning rate $\\eta$: $\\theta_{t+1} = \\theta_t - \\eta \\nabla \\mathcal{L}$.',
  'dropout': 'Tecnica di regolarizzazione per reti neurali: durante il training azzera casualmente una frazione dei neuroni, previene la co-adattazione.',
  'early stopping': 'Fermare l\'addestramento quando la loss di validazione smette di scendere. Regolarizzazione implicita.',
  'embedding': 'Rappresentazione densa a bassa dimensione di oggetti discreti (parole, utenti, prodotti). Alla base di word2vec, LLM, sistemi di raccomandazione.',
  'ensemble': 'Combinazione di più modelli (bagging, boosting, stacking) per ottenere prestazioni migliori del singolo.',
  'entropia': 'Misura di disordine di una distribuzione: $H(p) = -\\sum_c p_c \\log p_c$. Zero se un\'unica classe, massima con distribuzione uniforme.',
  'epoch': 'Un passaggio completo sul training set durante il training di una rete neurale.',
  'esempio': 'Un singolo elemento del dataset, di solito una coppia (x, y) per il supervisionato.',
  'F1': 'Media armonica di precision e recall: $F_1 = 2pr/(p+r)$. Metrica singola bilanciata per classificazione binaria.',
  'feature': 'Una variabile predittiva, cioè una colonna di X. Anche "predittore" o "attributo".',
  'feature engineering': 'Creazione di nuove feature da quelle esistenti (interazioni, trasformazioni, encoding categorie). Uno dei fattori più impattanti sulle performance.',
  'fold': 'Uno dei sottoinsiemi in cui si divide il dataset nella k-fold cross-validation.',
  'forward pass': 'Calcolo dell\'output di una rete neurale dato l\'input, strato per strato in avanti.',
  'generalizzazione': 'Capacità del modello di funzionare bene su dati mai visti. Il vero obiettivo del ML.',
  'gini': 'Impurità di Gini: $1 - \\sum_c p_c^2$. Usata negli alberi di decisione come criterio di split.',
  'gradiente': 'Vettore delle derivate parziali di una funzione. Punta nella direzione di massima crescita.',
  'gradient boosting': 'Algoritmo ensemble che costruisce modelli sequenzialmente, ognuno che apprende i residui del precedente. XGBoost, LightGBM, CatBoost.',
  'hyperparameter': 'Parametro non appreso dai dati ma fissato prima del training (es. learning rate, numero di alberi, C in SVM). Si tara con validation set o cross-validation.',
  'imputazione': 'Riempire valori mancanti con stime (media, mediana, moda, regressione, KNN). Farla dentro Pipeline per evitare leakage.',
  'inertia': 'Somma delle distanze quadrate dei punti dal proprio centroide in K-Means. Funzione obiettivo minimizzata.',
  'iperpiano': 'Sottospazio di dimensione $d-1$ in $\\mathbb{R}^d$. Un iperpiano separa lo spazio in due semispazi ed è la superficie di decisione dei classificatori lineari.',
  'k-fold': 'Cross-validation con K partizioni. Comune K=5 o K=10.',
  'k-means': 'Algoritmo di clustering che partiziona $n$ punti in $K$ cluster minimizzando la somma delle distanze al quadrato dai centroidi.',
  'k-NN': 'K-Nearest Neighbors. Predice come i K vicini più prossimi. Non-parametrico, semplice, potente ma lento in alta dimensione.',
  'kernel': 'Funzione $K(x, x\')$ che calcola implicitamente un prodotto scalare in uno spazio ad alta dimensione. Base del kernel trick nell\'SVM.',
  'label': 'La variabile target $y$ da predire nel supervisionato.',
  'lasso': 'Regressione lineare con penalità L1: $\\|Xw-y\\|^2 + \\lambda \\|w\\|_1$. Produce soluzioni sparse (feature selection).',
  'leakage': 'Data leakage. Contaminazione tra training e test tramite statistiche calcolate su tutto il dataset. Causa metriche gonfiate e fallimenti in produzione.',
  'learning rate': 'Fattore $\\eta$ che scala l\'aggiornamento del gradiente. Troppo grande: divergenza. Troppo piccolo: convergenza lenta.',
  'log-loss': 'Sinonimo di cross-entropy binaria: $-\\frac{1}{n}\\sum [y_i \\log p_i + (1-y_i)\\log(1-p_i)]$.',
  'logistic regression': 'Modello lineare per la classificazione binaria. Modella $\\log[p/(1-p)] = w^Tx + b$.',
  'MAE': 'Mean Absolute Error: $\\frac{1}{n}\\sum |y-\\hat y|$. Robusta agli outlier rispetto a MSE.',
  'MLE': 'Maximum Likelihood Estimation. Sceglie i parametri che massimizzano la probabilità dei dati osservati.',
  'MLP': 'Multi-Layer Perceptron. Rete neurale a strati densi (fully connected).',
  'MSE': 'Mean Squared Error: $\\frac{1}{n}\\sum (y-\\hat y)^2$. Loss standard per la regressione.',
  'normalizzazione': 'Portare i dati in una scala comune (es. [0,1]). Diverso da standardizzazione (media 0, std 1).',
  'one-hot encoding': 'Rappresentazione di variabile categorica con $K$ colonne binarie, una per categoria. Alternativa: target encoding, ordinal encoding.',
  'ottimizzatore': 'Algoritmo che aggiorna i parametri (SGD, Adam, RMSprop, AdaGrad). Adam è il default ragionevole.',
  'outlier': 'Punto anomalo, molto distante dalla distribuzione normale dei dati. Può essere errore o segnale, va investigato.',
  'overfitting': 'Il modello impara il rumore del training, non il pattern. Accuracy training alta, test bassa.',
  'PCA': 'Principal Component Analysis. Riduzione dimensionale che proietta i dati sulle direzioni di massima varianza.',
  'pipeline': 'Sequenza di step di preprocessing + modello incapsulata in un oggetto unico. Cruciale per evitare leakage in cross-validation.',
  'precision': 'Frazione di positivi predetti che erano davvero positivi: $TP/(TP+FP)$.',
  'preprocessing': 'Trasformazioni sui dati prima del modello: scaling, encoding, imputazione, feature engineering.',
  'random forest': 'Ensemble di alberi di decisione addestrati su bootstrap dei dati + random subset di feature ad ogni split.',
  'recall': 'Frazione di positivi veri che il modello ha catturato: $TP/(TP+FN)$. Sinonimo: sensibilità, TPR.',
  'regolarizzazione': 'Penalità sulla complessità del modello (L1, L2, dropout, weight decay) per prevenire overfitting.',
  'regressione': 'Compito supervisionato in cui $y$ è continuo (prezzo, temperatura, età).',
  'ReLU': 'Rectified Linear Unit: $\\max(0, z)$. Attivazione standard nelle reti neurali moderne.',
  'residuo': 'Differenza tra valore vero e predetto: $y - \\hat y$. Alla base del gradient boosting.',
  'ridge': 'Regressione lineare con penalità L2: $\\|Xw-y\\|^2 + \\lambda\\|w\\|^2$. Riduce coefficienti verso zero senza azzerarli.',
  'ROC': 'Receiver Operating Characteristic. Curva TPR vs FPR al variare della soglia. Area sotto = AUC.',
  'scaling': 'Trasformazione delle feature per portarle in scala comparabile. Standardizzazione: media 0, std 1. Cruciale per modelli distance-based (KNN, SVM) e neurali.',
  'sigmoid': 'Funzione $\\sigma(z) = 1/(1+e^{-z})$. Mappa reali in $(0,1)$. Usata come attivazione o per output di classificazione binaria.',
  'silhouette': 'Metrica di qualità di clustering, tra -1 e 1. Alto = cluster ben definito.',
  'softmax': 'Generalizzazione della sigmoide a $K$ classi: normalizza esponenziali a distribuzione di probabilità.',
  'sparse': 'Sparso. Un vettore/matrice con molti zeri. Le soluzioni Lasso sono sparse.',
  'stochastic gradient descent': 'SGD. Discesa del gradiente su mini-batch invece che sul dataset intero. Più veloce, aggiunge rumore utile.',
  'supervisionato': 'Apprendimento con dati etichettati $(x_i, y_i)$. Include classificazione e regressione.',
  'support vector': 'Punto di training con moltiplicatore di Lagrange non-nullo in SVM. Solo questi contribuiscono al modello.',
  'SVM': 'Support Vector Machine. Classificatore che massimizza il margine tra le classi. Con kernel non lineare (RBF) diventa modello universale.',
  'target': 'Sinonimo di label, la variabile $y$ da predire.',
  'test set': 'Sottoinsieme di dati usato SOLO alla fine per stimare la generalizzazione. Guardarlo durante lo sviluppo lo trasforma in un secondo val set.',
  'training set': 'Sottoinsieme di dati usato per addestrare il modello.',
  'transfer learning': 'Riusare un modello pre-addestrato su un problema simile, con eventualmente fine-tuning.',
  'true positive': 'TP. Esempio positivo correttamente classificato come positivo.',
  'underfitting': 'Il modello è troppo semplice per catturare il pattern. Training e test entrambe con errore alto.',
  'validation set': 'Sottoinsieme separato dal training usato per scegliere iperparametri e modello. Diverso dal test.',
  'varianza': 'In statistica: $\\mathrm{Var}(X) = \\mathbb{E}[(X-\\mathbb{E}X)^2]$. Nel bias-variance tradeoff: quanto le predizioni cambiano con dati diversi.',
  'vettorializzazione': 'Sostituire loop Python con operazioni NumPy su interi array. 50-500x più veloce.',
  'XGBoost': 'Libreria di gradient boosting altamente ottimizzata. Standard de facto per dati tabulari.',  'gradient boosting': 'Ensemble sequenziale di alberi dove ogni albero fa un passo di gradient descent nello spazio delle funzioni, imparando i residui/gradienti del precedente. Standard per dati tabulari (XGBoost, LightGBM, CatBoost, HistGradientBoosting).',
  'HistGradientBoosting': 'Implementazione sklearn di gradient boosting con histogram splitting, ispirata a LightGBM. Gestisce NaN nativamente, molto veloce, disponibile senza dipendenze esterne.',
  'LightGBM': 'Libreria di gradient boosting di Microsoft. Histogram-based, leaf-wise growth, molto veloce. Spesso il default in produzione.',
  'CatBoost': 'Libreria di gradient boosting di Yandex ottimizzata per feature categoriche. Ordered boosting, gestione nativa delle categoriche.',
  'early stopping': 'Interrompere il training quando la loss di validazione smette di scendere per N iterazioni. Trova automaticamente il numero ottimo di alberi/epoch senza tunare a mano.',
  'target encoding': 'Sostituire una categoria con la media (o altra statistica) di y per quella categoria. Potente per alta cardinalità ma soggetto a leakage: va fatto out-of-fold + smoothing.',
  'smoothing': 'Tecnica per rendere robuste stime su categorie rare, media pesata tra stima locale e stima globale. Fondamentale nel target encoding.',
  'permutation importance': 'Misurare l importanza di una feature mescolandone i valori e osservando quanto peggiora la performance. Model-agnostic, meno biased delle feature importance native.',
  'SHAP': 'SHapley Additive exPlanations. Metodo game-theory per spiegare predizioni di modelli complessi, attribuendo un contributo a ogni feature. Gold standard di interpretabilità.',
  'encoding ciclico': 'Rappresentare feature cicliche (ora del giorno, giorno della settimana) con seno/coseno per preservare la distanza tra 23:00 e 00:00.',
  'ColumnTransformer': 'Utility sklearn per applicare trasformazioni diverse a diversi sottoinsiemi di colonne (es. scaling per numeriche, one-hot per categoriche) dentro una pipeline.',
  'nested CV': 'Cross-validation con due livelli: outer per stimare la performance, inner per selezionare iperparametri. Unica stima onesta di performance con tuning.',
  'walk-forward validation': 'Validazione per time series: si addestra su tutto il passato fino a t, si valida su t+1..t+k, si avanza. Preserva la causalità temporale.',
  'calibrazione': 'Un modello è ben calibrato se predice probabilità che riflettono le frequenze osservate (es. quando dice 90% è positivo il 90% delle volte). Diverso dal ranking (misurato da AUC).',
  'Brier score': 'Metrica di calibrazione: media dei quadrati degli errori tra probabilità predetta e outcome binario. Più basso = meglio calibrato.',
  'PR-AUC': 'Area sotto la curva Precision-Recall. Preferibile a ROC-AUC con classi molto sbilanciate perché non ricompensa i negativi facili.',
  'MCC': 'Matthews Correlation Coefficient. Metrica di classificazione binaria robusta allo sbilanciamento. Va da -1 (predizioni opposte) a 1 (perfette), 0 = casuale.',
  'target leakage': 'Feature che contengono informazione sul target non disponibile in produzione. Causa performance gonfiate in test che poi crollano in produzione.',
  'IterativeImputer': 'Imputer sklearn che stima ogni feature mancante come funzione delle altre iterativamente. Sofisticato ma lento.',
  'binning': 'Discretizzare feature continue in intervalli. Strategie: equal-width, equal-frequency, k-means.',
  'RobustScaler': 'Scaler basato su mediana e IQR invece che media/std. Robusto agli outlier.',

  'CNN': 'Convolutional Neural Network. Rete neurale specializzata per dati con struttura spaziale (immagini). Usa convoluzioni + pooling per estrarre feature gerarchiche.',
  'convoluzione': 'Operazione di filtro locale: un kernel scivola sull immagine e a ogni posizione calcola una somma pesata. Base delle CNN.',
  'kernel_conv': 'In CNN, un piccolo tensore di pesi (es. 3x3) applicato a ogni posizione dell input. La rete impara i valori del kernel.',
  'pooling': 'Riduzione dimensionale in CNN. Max pooling prende il massimo di ogni finestra; average pooling la media. Introduce invarianza a piccole traslazioni.',
  'stride': 'Passo con cui un kernel di convoluzione o pooling scivola. Stride 2 dimezza le dimensioni dell output.',
  'padding': 'Aggiunta di zeri ai bordi dell input per preservare la dimensione dopo la convoluzione. Same padding: output uguale a input.',
  'residual connection': 'Skip connection y = F(x) + x. Introdotta da ResNet, permette al gradiente di fluire attraverso reti profonde risolvendo il vanishing gradient.',
  'batch normalization': 'Normalizzazione delle attivazioni per batch. Stabilizza il training, permette lr più alti, agisce da leggero regolarizzatore.',
  'transfer learning': 'Riusare un modello pre-addestrato (es. ResNet su ImageNet) adattandolo a un nuovo task. Riduce enormemente dati e tempo di training richiesti.',
  'fine-tuning': 'Continuare l addestramento di un modello pre-addestrato sul proprio task, tipicamente con lr piccolo per non distruggere le feature apprese.',
  'data augmentation': 'Aumentare artificialmente il training set con trasformazioni (flip, crop, rotazione per immagini). Fortissimo regolarizzatore.',
  'PyTorch': 'Framework Python per deep learning con autograd automatico. Standard nella ricerca e sempre più in produzione. Alternative: TensorFlow, JAX.',
  'autograd': 'Sistema di differenziazione automatica dei framework moderni. Scrivi il forward, i gradienti sono calcolati dal framework.',
  'Adam': 'Ottimizzatore che combina momentum e adaptive learning rate per parametro. Default ragionevole per la maggior parte dei casi. lr tipico: 1e-3.',
  'momentum': 'Aggiunta di inerzia al gradient descent: v_t = gamma * v_{t-1} + eta * gradient. Accelera in direzioni consistenti, smorza oscillazioni.',
  'weight decay': 'Regolarizzazione L2 sui pesi. Equivalente a shrinkage. In Adam corretto è AdamW.',
  'ResNet': 'Rete convoluzionale con residual connections (2015). Permise reti da 50-1000 layer, vinse ImageNet.',
  'MLflow': 'Framework open-source per experiment tracking, model registry e deployment. Standard per MLOps.',
  'FastAPI': 'Framework Python moderno per API REST. Async, validazione automatica con Pydantic, docs OpenAPI generate.',
  'Docker': 'Piattaforma di containerizzazione. Impacchetta app + dipendenze in container isolati riproducibili ovunque.',
  'data drift': 'La distribuzione delle feature in produzione differisce da quella di training. Causa degradation del modello nel tempo.',
  'concept drift': 'La relazione input-output cambia nel tempo. Esempio: pattern di frode evolvono, i frodatori imparano.',
  'PSI': 'Population Stability Index. Metrica di drift: <0.1 stabile, 0.1-0.2 lieve, >0.2 significativo. Somma pesata di log-ratio delle frequenze binnate.',
  'canary deployment': 'Rilascio graduale: il nuovo modello serve prima il 5% del traffico, poi 20%, 50%, 100% se le metriche sono buone.',
  'A/B test': 'Suddividi utenti in gruppi (controllo con modello vecchio, treatment con nuovo) e confronti metriche di business con test statistici.',
  'model registry': 'Servizio che versiona modelli con metadata (metriche, dati di training, autore). MLflow Model Registry, Weights & Biases Artifacts.',
  'feature store': 'Repository centralizzato di feature calcolate, con garanzia di consistenza tra training e serving. Feast, Tecton.',
  'training-serving skew': 'Discrepanza tra come le feature sono calcolate in training vs inference. Causa comune di modelli che funzionano male in produzione.',
  'ONNX': 'Open Neural Network Exchange. Formato aperto per modelli ML, permette portabilità tra framework (sklearn, PyTorch, TensorFlow) e ottimizzazioni di inference.',
  'joblib': 'Libreria Python per serializzazione efficiente di oggetti Python con array numpy. Default per salvare modelli sklearn.',
  'cost-sensitive learning': 'Approccio in cui i costi asimmetrici degli errori (FN vs FP) sono incorporati nella loss o nella soglia di decisione.',
  'imbalanced classification': 'Classificazione con classi molto sbilanciate (fraud, medical rare disease). Richiede metriche e tecniche specifiche.',
  'SMOTE': 'Synthetic Minority Over-sampling Technique. Genera esempi sintetici della classe minoritaria interpolando tra vicini. Da usare DENTRO pipeline per evitare leakage.',

};
